stages:
  - test
  - build

# Этап тестирования
test:
  stage: test
  image: golang:1.17
  script:
    - echo "Запускаем тесты Go..."
    - go test -v ./...
  tags:
    - docker

# Этап сборки Docker образа
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Собираем Docker образ..."
    - docker build -t my-first-ci:latest .
  tags:
    - docker
